language: node_js
sudo: true
node_js:
- 6.11.5
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: github.com
before_install:
- openssl aes-256-cbc -K $encrypted_b231c297449e_key -iv $encrypted_b231c297449e_iv
  -in ./.travis/server_key.enc -out server_key -d
- openssl aes-256-cbc -K $encrypted_b231c297449e_key -iv $encrypted_b231c297449e_iv
  -in ./.travis/deploy_key.enc -out deploy_key -d
- bash ./.travis/init.sh
- bash ./.travis/clone.sh
script:
- npm run build
- bash ./.travis/deploy.sh
branches:
  only:
  - dev
  - release
  - master
