language: node_js
sudo: true
node_js:
- 6.11.5
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - github.com
  - bitbucket.org
before_install:
- bash ./.travis/init.sh
- bash ./.travis/clone.sh
script:
- npm run build
- bash ./.travis/deploy.sh
branches:
  only:
  - dev
  - release
  - master
