language: node_js
sudo: true
node_js:
- 6.11.5
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - github.com
  - bitbucket.org
before_install:
- openssl aes-256-cbc -K $encrypted_b231c297449e_key -iv $encrypted_b231c297449e_iv
  -in .travis/assets.zip.enc -out assets.zip -d
- npm install -g npx
- npm install -g pm2
- bash ./.travis/scripts/init.sh
- bash ./.travis/scripts/clone.sh
script:
- npm run build
- bash ./.travis/scripts/deploy.sh
branches:
  only:
  - dev
  - release
  - master
